services:
  - type: web
    name: youtube-links-scraper
    env: docker
    buildCommand: docker build -t youtube-links-scraper .
    startCommand: gunicorn --config gunicorn.conf.py app:app
    envVars:
      - key: PORT
        value: 5000
      - key: PYTHONUNBUFFERED
        value: 1
