services:
  - type: web
    name: youtube-links-scraper
    env: docker
    buildCommand: docker build -t youtube-links-scraper .
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PORT
        value: 5000
